//up-072
//down-080
//left-075
//right-077
#include<iostream.h>
#include<conio.h>
void car()
{
 char control
  cout<<"                 \n";
  cout<<"                 \n";
  cout<<"                 \n";
  cout<<"                 \n";
  cout<<"                 \n";
  cout<<"                 \n";
  cout<<"                 \n";
  cout<<"                 \n";
  cout<<"                                                                \n";
  cout<<"          /\\            /\\            /\\            /\\            /\\        \n";
  cout<<"        /    \\        /    \\        /    \\        /    \\        /    \\        \n";
  cout<<"      /        \\    /        \\    /        \\    /        \\    /        \\      \n";
  cout<<"    /            \\/            \\/            \\/            \\/            \\     \n";
  cout<<"________________________________________________________________________________       \n";
  cout<<"                                    /      \\                    \n";
  cout<<"                                  /          \\                  \n";
  cout<<"                                /              \\ 		     \n";
  cout<<"                              /                  \\ 	     \n";
  cout<<"                            /       _________      \\              "<<endl;
  cout<<"                          /        //_______\\\\       \\          "<<endl;
  cout<<"                        /        ---------------       \\          " <<endl;
  cout<<"                      /         | 0 |THUGLYF| 0 |        \\        "<<endl;
  cout<<"                    /            ---------------           \\      " <<endl;
  cout<<"                  /                |_|     |_|               \\    "<<endl;
}
void main()
{
  clrscr();
  car();



  getch();
}