/*
Program No	: 02
Developed By	: Aniansh Raj Singh, Akshat Ayush
Class		: XI G
Date		: 22-July-2016
*/
#include<iostream.h>
#include<conio.h>
void main()
{
 clrscr();
 float R,C,A ;
 cout<< "Welcome to the program!\n";
 cout<<"Please type in the radius of the circle!(in cm)\n";
 cin>> R;
 C=2*3.14*R;
 A=3.14*R*R;
 cout<<"The Circumference = "<< C<<" cm sq\nAnd the Area = ";
 cout<< A<<" cm cubed\n";
 getch();
}

/*  OUTPUT
  Welcome to the program!
  Please type in the radius of the circle!(in cm)
  7
  The Circumference = 43.959999 cm sq
  And the Area = 153.860001 cm cubed
*/

                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
